# user-db-volume.yml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mssql-user-pv
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/mssql-user

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mssql-user-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
