# userserviceapi.yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
      - name: apigateway
        image: my-apigateway
        imagePullPolicy: Never
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: FLUENTD_HOST
          value: "fluentd"
        - name: FLUENTD_PORT
          value: "24224"
        - name: API_GATEWAY_URL
          value: "http://apigateway"
      initContainers:
      - name: wait-for-db
        image: busybox
        command: ["sh", "-c", "until nc -z user-db 1433; do echo waiting for db; sleep 2; done;"]
---
apiVersion: v1
kind: Service
metadata:
  name: apigateway
  namespace: default
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
  selector:
    app: apigateway