services:
  user-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      MSSQL_SA_PASSWORD: "SuperSecret7!"
      ACCEPT_EULA: "Y"
    volumes:
      - mssql-user:/var/opt/mssql
    ports:
      - "1433:1433"
    healthcheck:
      test: [ "CMD-SHELL", "pgrep sqlservr" ]
      interval: 10s
      retries: 1
      start_period: 60s
      timeout: 5s

  ApiGateWay:
    build:
      context: .
      dockerfile: ApiGateWay/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - userService
      - LoginService
        
  userService:
    build:
      context: .
      dockerfile: UserService/Dockerfile
    depends_on:
      user-db:
        condition: service_healthy
      rmq:
        condition: service_healthy
  
  LoginService:
    build:
      context: .
      dockerfile: LoginService/Dockerfile
    depends_on:
      user-db:
        condition: service_healthy
      rmq:
        condition: service_healthy
  
  rmq:
    image: rabbitmq:management
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=application
      - RABBITMQ_DEFAULT_PASS=pepsi
    healthcheck:
      test: [ "CMD-SHELL", "pgrep rmq" ]
      interval: 10s
      retries: 1
      start_period: 60s
      timeout: 5s

  migration_service:
    build:
      context: .
      dockerfile: ApiGateWay/Migrations.Dockerfile
    depends_on:
      user-db:
        condition: service_healthy

volumes:
  mssql-user: